export const HomeAboutTourData = [
  {
    id: 1,
    img: `/Media/Home/pic1.jpg`,
    title: `राहुल सांकृत्यायन भवन`,
    title2: `Rahul Sankrityayan Bhawan`,
    subtitle: `(लेखक अतिथि गृह)`,
    subtitle2: `(Writer's Guest House)`,
    desc: `लेखक गांव में आने वाले छात्रों,शोधार्थियों,लेखकों,रचनाकारों,प्रकृति प्रेमियों आदि आगंतुकों हेतु शांत एवं सौंदर्यपूर्ण परिवेश में आवश्यक सुविधाओं से युक्त अतिथिगृह स्थापित है। अतिथिगृह की आवासीय व्यवस्था आगंतुकों के आरामदायक प्रवास के साथ ही रचनात्मकता का अवसर प्रदान करेगा।`,
    desc2: `A guest house equipped with necessary facilities has been set up in a peaceful and beautiful environment for the students, researchers, writers, authors, nature lovers etc. who come to Lekhak Gaon. The residential arrangement of the guest house will provide a comfortable stay to the visitors as well as an opportunity for creativity.`,
    descBoxClass: `bg-[#ef8d9d]`,
  },
  {
    id: 2,
    img: `/Media/Home/2.png`,
    title: `रम्माण भवन`,
    title2: `Ramman Bhawan`,
    subtitle: `(प्रेक्षागृह)`,
    subtitle2: `(Auditorium)`,
    desc: ` लेखक गांव का प्रेक्षागृह आधुनिक सुविधाओं से परिपूर्ण भव्य सभागार है। लगभग एक हजार क्षमतायुक्त में साहित्यिक,सांस्कृतिक,आध्यात्मिक,धार्मिक,तथा समस्त रचनात्मक विविधतापूर्ण समारोहों और कार्यक्रमों  के नियमित आयोजन से लेखक गांव के उद्देश्यों के लक्ष्यों को प्राप्त किया जा सकेगा।`,
    desc2: `The auditorium of the writer's village is a grand auditorium equipped with modern facilities. The objectives of the writer's village can be achieved by regularly organizing literary, cultural, spiritual, religious and all creative diverse events and programs in the auditorium with a capacity of about one thousand.`,
    descBoxClass: `bg-[#ed5864]`,
  },
  {
    id: 3,
    img: `/Media/Home/pic3.jpg`,
    title: `नालंदा भवन`,
    title2: `Nalanda Bhawan`,
    subtitle: `(पुस्तकालय)`,
    subtitle2: `(Library)`,
    desc: `हिमालय गांव का यह पुस्तकालय भारत के गौरव नालंदा ग्रन्थालय के वैभव से प्रेरित पुस्तकालय में समस्त विषयों की पुस्तकों के संकलन के संग्रह कवप्रयास है। पुस्तकालय में परम्परागत ज्ञान परम्परा पर आधारित पुस्तकों सहित आधुनिक विषयों पर केंद्रित पुस्तकों का संकलन होगा। देश के प्रत्येक अंचल का साहित्य,संस्कृति,इतिहास,पुरातत्व, राजनीति,भूगोल, धर्म,दर्शन सहित सभी विषयों पर केंद्रित यह पुस्तकाल आगंतुकों के रचनाधर्मिता के साथ उनके ज्ञान और जानकारियों को विस्तारित करने का प्रयास होगा।`,
    desc2: `This library of Himalaya village is an attempt to collect books on all subjects in a library inspired by the glory of Nalanda Library, the pride of India. The library will have a collection of books based on traditional knowledge and books on modern subjects. This library, focused on all subjects including literature, culture, history, archeology, politics, geography, religion, philosophy of every region of the country, will be an attempt to expand the knowledge and information of the visitors along with their creativity.`,
    descBoxClass: `bg-[#ff009d]`,
  },
  {
    id: 4,
    img: `/Media/Home/pic4.jpg`,
    title: ` द्रोणागिरी भवन`,
    title2: `Dronagiri Bhavan`,
    subtitle: `(प्राकृतिक चिकित्सा केंद्र)`,
    subtitle2: `(Naturopathy and Ayurveda Centre)`,
    desc: `लेखक  गांव का यह केंद्र प्राकृतिक चिकित्सा के साथ आयुर्वेद चिकित्सा पद्धति से स्वस्थ शरीर और प्रसन्न चित्त की अवधारणा पर लेखक गांव में प्रवास करने वाले अतिथियों की अपनी सुविधाएं प्रदान करेगा।  पंचकर्म सहित आयुर्वेद की महत्वपूर्ण चिकित्सा पद्धति को प्रतिष्ठित चिकित्सकों के माध्यम से संचालित किया जा सकेगा।`,
    desc2: `This centre of Writer's Village will provide its facilities to the guests staying in Writer's Village on the concept of healthy body and happy mind through Ayurveda medical system along with naturopathy. Important medical system of Ayurveda including Panchkarma will be operated through reputed doctors.`,
    descBoxClass: `bg-[#474eff]`,
  },
  {
    id: 5,
    img: `/Media/Home/pic5.jpg`,
    title: `महर्षि व्यास भवन`,
    title2: `Maharishi Vyas Bhavan`,
    subtitle: `(ध्यान केंद्र)`,
    subtitle2: `(Meditation Centre)`,
    desc: `लेखक गांव का महर्षि व्यास ध्यान केंद वर्तमान समय में मानव की विचलित एवं भटकाव की प्रवृत्ति को एकाग्र और शांत चित्त रखने की अभ्यासशाला है। लेखक गांव के आगंतुक इस केंद्र में योगाचार्यों के निर्देशन में योग तथा ध्यान का अभ्यास कर अपने तन और मन की प्रफुल्लित कर सकेंगे।`,
    desc2: `Maharishi Vyas Dhyan Kendra of Lekhak Village is a practice centre to keep the mind focused and calm in the present times when humans are distracted and wandering. Visitors of Lekhak Village will be able to make their body and mind happy by practising yoga and meditation under the guidance of yoga teachers in this centre.`,
    descBoxClass: `bg-[#ff9b29]`,
  },
  {
    id: 6,
    img: `/Media/Home/pic6.jpg`,
    title: `महर्षि कण्व भवन`,
    title2: `Maharishi Kanva Bhavan`,
    subtitle: `(परम्परागत ज्ञान विज्ञान केंद्र)`,
    subtitle2: `(Traditional Knowledge and Science Centre)`,
    desc: ` लेखक गांव का यह केंद्र भारत की गौरशाली परंपरागत ज्ञान विज्ञान की विविधताओं से आगंतुकों को अवगत कराएगा। इस केंद्र में ज्योतिष विज्ञान केंद्र का प्रारूप महत्वपूर्ण होगा। ज्योतिषाचार्य एवं वास्तुशास्त्री इस केंद्र में आगंतुकों को उनके प्रश्नों तथा शंकाओं का निराकरण करेंगे।`,
    desc2: `This centre of Lekhak Gaon will make the visitors aware of the diversity of India's glorious traditional knowledge and science. The format of Jyotish Vigyan Kendra will be important in this centre. Jyotishacharya and Vastu Shastra experts will solve the questions and doubts of the visitors in this centre.`,
    descBoxClass: `bg-[#05854d]`,
  },
  {
    id: 7,
    img: `/Media/Home/pic3.jpg`,
    title: `नीलकंठ भवन`,
    title2: `Neelkanth Bhawan`,
    subtitle: `(हिमालय एवं गंगा संग्रहालय)`,
    subtitle2: `(Himalayas and Ganga Museum)`,
    desc: `लेखक गांव का यह केंद्र हिमालय  और गंगा के वैभव को संजोए सबसे आकर्षण के केंद्र के रूप में स्थापित किया जा रहा है। सत्यम शिवम सुंदरम के अनुरूप हिमालय की प्रकृति,संस्कृति,लोक कला,ज्ञान विज्ञान,वेद आयुर्वेद ,योग ध्यान,कला,उत्सव,लोक जीवन,खान पान,परम्परा आदि आदि विविध विषयों की झलक इस संग्रहालय की विशेषता होगी।`,
    desc2: `This centre of Lekhak Gaon is being established as the centre of attraction preserving the splendour of Himalayas and Ganga. In accordance with Satyam Shivam Sundaram, glimpses of various subjects like nature, culture, folk art, knowledge science, Vedas Ayurveda, yoga meditation, art, festivals, folk life, food, tradition etc. of Himalayas will be the specialty of this museum.`,
    descBoxClass: `bg-[#ff61a8]`,
  },
  {
    id: 8,
    img: `/Media/Home/pic4.jpg`,
    title: `लेखक कुटीर`,
    title2: `Author's Cottage`,
    subtitle: ``,
    subtitle2: `(Creative Living Cottages)`,
    desc: `लेखक गांव में निर्मित अपनी आकर्षक वास्तु एवं शिल्प से परिपूर्ण लेखक कुटीर रचनाधर्मियों के लिए शांति और सौंदर्य में आवास का आमंत्रण है। लेखक गांव की विविध कुटीर जैसे आदि कवि कालिदास कुटीर, कवि सुमित्रानंदन पंत कुटीर,कवि रवीन्द्रनाथ टैगोर कुटीर,कवि चंद्रकुंवर  कुटीर,  शिव प्रसाद डबराल कुटीर आदि आदि परिवेश को रचनात्मकता और सृजन के परिवेश से  सहजता से जोड़ने का प्रयास करती हैं`,
    desc2: `The Lekhak Kutir built in Lekhak Village with its attractive architecture and craftsmanship is an invitation for creative people to live in peace and beauty. Various cottages of Lekhak Village like Adi Kavi Kalidas Kutir, Kavi Sumitranandan Pant Kutir, Kavi Rabindranath Tagore Kutir, Kavi Chandrakunwar Kutir, Shiv Prasad Dabral Kutir etc. try to connect the environment with the environment of creativity and creation.`,
    descBoxClass: `bg-[#ff6161]`,
  },
  {
    id: 9,
    img: `/Media/Home/pic5.jpg`,
    title: `सुंदर लाल बहुगुणा`,
    title2: `Sunder Lal Bahuguna`,
    subtitle: `(पर्यावरण पथ)`,
    subtitle2: `(Environmental Path)`,
    desc: `लेखक गांव के पूरे परिवेश में एक भ्रमण पथ विकसित किया जा रहा है। इस पथ पर लेखक गांव के आगंतुक अपनी प्रातः और सांय की सैर करेंगे। यह पथ उन्हें पर्यावण के चिंतन की भावना से जोड़ते हुए तन मन की प्रफुल्लता प्रदान करेगा। भ्रमण के दौरान फूल पत्तियों सहित पंछियों तितलियों का कलरव अतिथियों की प्रवृत्ति से  स्वतः जुड़ सकेगा|`,
    desc2: `A walking path is being developed in the entire surroundings of the writer's village. Visitors to the writer's village will take morning and evening walks on this path. This path will provide them with a sense of contemplation of the environment and will provide them with a sense of happiness. During the walk, the chirping of flowers, leaves, birds and butterflies will automatically connect with the tendency of the guests.`,
    descBoxClass: `bg-[#2699fb]`,
  },
];

export const HomeSliderData = [
  {
    id: 1,
    bgImg: `bg-[url('/Media/About/39.jpg')]`,
    img: `/Media/About/10.jpg`,
    title: `सोनल मान सिंह (भारतीय शास्त्रीय नृत्यांगना)`,
    title2: `Sonal Mansingh (Indian Classical Dancer)`,
    subtitle: `()`,
    subtitle2: ``,
    desc: `मेरे लिए प्रकृति के इस सौंदर्य के बीच अपनी कला का प्रदर्शन और प्रस्तुति देना एक अलग अनुभूति है`,
    desc2: `For me, it is a different feeling to exhibit and present my art amidst this beauty of nature`,
  },
  {
    id: 2,
    bgImg: `bg-[url('/Media/About/40.jpg')]`,
    img: `/Media/About/2.jpg`,
    title: `स्वामी अवधेशानंद गिरि जी महाराज (हिंदू आध्यात्मिक गुरु, संत, लेखक और दार्शनिक)`,
    title2: `Swami Avdheshanand Giri Ji Maharaj (Hindu Spiritual Guru, Saint, Author, and Philosopher)`,
    subtitle: `()`,
    subtitle2: ``,
    desc: `यह गांव सृजन का गाँव बनेगा। अपने आप में यह अबतक की अनोखी और विशेष पहल है, मुझे आशा ही नहीं विश्वास भी है कि यह रचनाकारों के लिए वरदान साबित होगा।`,
    desc2: `This village will become a village of creation. This is a unique and special initiative in itself, I not only hope but also believe that this will prove to be a boon for creators.`,
  },
  {
    id: 3,
    bgImg: `bg-[url('/Media/About/41.jpg')]`,
    img: `/Media/About/3.jpg`,
    title: `प्रसून जोशी (हिन्दी कवि, लेखक, पटकथा लेखक और भारतीय सिनेमा के गीतकार)`,
    title2: `Prasoon Joshi (Hindi Poet, Writer, Screenwriter, and Lyricist of Indian Cinema)`,
    subtitle: `()`,
    subtitle2: ``,
    desc: `हिमालय में यह गांव रचनात्मकता को विस्तार देगा। किसी भी रचना की उत्पत्ति के लिए एकांत और सृजनात्मक माहौल की आवश्यकता होती है, जिससे रचनाकार अपने स्वयं के अस्तित्व में डूब कर मोती निकाल सके और यह लेखक गाँव वही साबित होगा|`,
    desc2: `This village in the Himalayas will expand creativity. For the creation of any creation, solitude and a creative environment is required, so that the creator can immerse himself in his own existence and extract pearls and this writer's village will prove to be just that.`,
  },
];

