export const MediaMainData = [
  { id: 1, type: "image", img: `/Media/About/1.jpg` },
  { id: 2, type: "image", img: `/Media/About/2.jpg` },
  { id: 3, type: "image", img: `/Media/About/3.jpg` },
  { id: 4, type: "image", img: `/Media/About/4.jpg` },
  { id: 5, type: "image", img: `/Media/About/5.jpg` },
  { id: 6, type: "image", img: `/Media/About/6.jpg` },
  { id: 7, type: "image", img: `/Media/About/7.jpg` },
  { id: 8, type: "image", img: `/Media/About/8.jpg` },
  { id: 9, type: "image", img: `/Media/About/9.jpg` },
  { id: 10, type: "image", img: `/Media/About/10.jpg` },
  { id: 11, type: "image", img: `/Media/About/11.jpg` },
  { id: 12, type: "image", img: `/Media/About/12.jpg` },
  { id: 13, type: "image", img: `/Media/About/13.jpg` },
  { id: 14, type: "image", img: `/Media/About/14.jpg` },
  { id: 15, type: "image", img: `/Media/About/15.jpg` },
  { id: 16, type: "image", img: `/Media/About/16.jpg` },
  { id: 17, type: "image", img: `/Media/About/17.jpg` },
  { id: 18, type: "image", img: `/Media/About/18.jpg` },
  { id: 19, type: "image", img: `/Media/About/19.jpg` },
  { id: 20, type: "image", img: `/Media/About/20.jpg` },
];

export const MediaPicsData = [
  { id: 1, type: "image", img: `/Media/About/1.jpg` },
  { id: 2, type: "image", img: `/Media/About/2.jpg` },
  { id: 3, type: "image", img: `/Media/About/3.jpg` },
  { id: 4, type: "image", img: `/Media/About/4.jpg` },
  { id: 5, type: "image", img: `/Media/About/5.jpg` },
  { id: 6, type: "image", img: `/Media/About/6.jpg` },
  { id: 7, type: "image", img: `/Media/About/7.jpg` },
  { id: 8, type: "image", img: `/Media/About/8.jpg` },
  { id: 9, type: "image", img: `/Media/About/9.jpg` },
  { id: 10, type: "image", img: `/Media/About/10.jpg` },
  { id: 11, type: "image", img: `/Media/About/11.jpg` },
  { id: 12, type: "image", img: `/Media/About/12.jpg` },
  { id: 13, type: "image", img: `/Media/About/13.jpg` },
  { id: 14, type: "image", img: `/Media/About/14.jpg` },
  { id: 15, type: "image", img: `/Media/About/15.jpg` },
  { id: 16, type: "image", img: `/Media/About/16.jpg` },
  { id: 17, type: "image", img: `/Media/About/17.jpg` },
  { id: 18, type: "image", img: `/Media/About/18.jpg` },
  { id: 19, type: "image", img: `/Media/About/19.jpg` },
  { id: 20, type: "image", img: `/Media/About/20.jpg` },
  { id: 21, type: "image", img: `/Media/About/21.jpg` },
  { id: 22, type: "image", img: `/Media/About/22.jpg` },
  { id: 23, type: "image", img: `/Media/About/23.jpg` },
  { id: 24, type: "image", img: `/Media/About/24.jpg` },
  { id: 25, type: "image", img: `/Media/About/25.jpg` },
  { id: 26, type: "image", img: `/Media/About/26.jpg` },
  { id: 27, type: "image", img: `/Media/About/27.jpg` },
  { id: 28, type: "image", img: `/Media/About/28.jpg` },
  { id: 29, type: "image", img: `/Media/About/29.jpg` },
  { id: 30, type: "image", img: `/Media/About/30.jpg` },
  { id: 31, type: "image", img: `/Media/About/31.jpg` },
  { id: 32, type: "image", img: `/Media/About/32.jpg` },
  { id: 33, type: "image", img: `/Media/About/33.jpg` },
  { id: 34, type: "image", img: `/Media/About/34.jpg` },
  { id: 37, type: "image", img: `/Media/About/37.jpg` },
  { id: 35, type: "image", img: `/Media/About/35.jpg` },
];

export const MediaVideoData = [
  {
    id: 1,
    src: `https://www.youtube.com/embed/mMdVy9fQMy8?si=EEmisknqoz_YufrW`,
  },
  {
    id: 2,
    src: `https://www.youtube.com/embed/nr1jpvXvyCY?si=stG0Pxt_alsBQ2fP`,
  },
  {
    id: 3,
    src: `https://www.youtube.com/embed/AgLy122chlQ?si=ayzTAWvznJB1CK_J`,
  },
];
