export const OurVisionData = [
  {
    id: 1,
    title: `हिमालय विश्व के लिए केवल आस्था और आध्यात्म का केंद्र ही नही है बल्कि रहस्य, रोमांच,ज्ञान,विज्ञान, वेद आयुर्वेद ,शांति और सौंदर्य आदि आदि विषयों की प्रयोगशाला है. यही कारण है कि सदियों सदियों से देवी देवताओं,ऋषि मुनियों,दार्शनिक,चिंतकों,कलाप्रेमियो एवम लेखकों सहित आम जनमानस का उत्तराखंड हिमालय प्रिय गंतव्य  स्थल है. ये भूमि सृजन की भूमि है जहां शांति में कल्पनाओं को विस्तार मिलता है तो हम  शांति और सौंदर्य में रचते बसते हैं,गुनगुनाते हैं, चिंता से दूर चिंतन से  सीखते हैं तो लिखते हैं और रचते हैं. शिवालिक पहाड़ियों की सुंदर तलहटी में उत्तराखंड हिमालय और गंगा के निकट आपकी कल्पनाओं को विस्तार देने के लिए एक गांव की स्थापना की जा रही है.. लेखक गांव।`,
    title2: `The Himalayas are not just a center of faith and spirituality for the world but also a laboratory of mysteries, adventure, knowledge, science, Vedas, Ayurveda, peace, and beauty. This is why, for centuries, the Uttarakhand Himalayas have been a beloved destination for deities, sages, philosophers, thinkers, art lovers, writers, and the common people alike. This land is a land of creation, where imagination finds expansion in peace. Here, we immerse ourselves in tranquility and beauty, hum melodies, stay away from worries, learn through contemplation, write, and create. Amidst the beautiful foothills of the Shivalik range, near the Uttarakhand Himalayas and the sacred Ganges, a village is being established to nurture your imagination— "Lekhak Gaon" (Writers' Village).`,
  },
  {
    id: 2,
    title: `आपके रचने के लिए तथा आपके रहने के लिए. ये गांव जो आपको हिमालय और गंगा का सानिध्य देता है, इसका परिवेश आपके तन और मन को स्फूर्ति प्रदान करता है. यहां सौंदर्य है यहां शांति है. आपके चिंतन के लिए यहां से विविधता के विषय  दृष्टिकोण प्राप्त होंगे तो आप लेखक हैं,कवि हैं,चित्रकार हैं,छायाकार हैं या सैलानी.  इस गांव को अपना आधार स्थल बनाइए और विविध स्थलों का भ्रमण कर कुछ रचिए. लेखक गांव की लेखक कुटीर,आवासीय परिसर,पुस्तकालय,कला दीर्घा, योग ध्यान केंद्र,परिचर्चा केंद्र, मनोरंजन केंद्र आदि सुविधाएं आपके तन और मन में स्फूर्ति प्रदान करने में सहायता प्रदान करती हैं. लेखक गांव की परिकल्पना केवल एक आधारभूत संरचना नही है ये ऐसे श्रेष्ठतम लेखकों और रचनाकारों  को सम्मान दिलाने के अवसर प्रदान करेगा जिनकी रचनात्मकता उनकी विषमताओं से बाधित हो रही है. ऐसे नवोदित रचनाकारों को  प्रोत्साहन के साथ उनके कौशल विकास को विकसित करने का प्रयास भी करेगा जो सृजनशील हैं.`,
    title2: `A place for you to create and reside, this village offers the serene presence of the Himalayas and the Ganges, rejuvenating both body and mind with its tranquil and beautiful surroundings. Here, you will find inspiration in diverse perspectives, whether you are a writer, poet, painter, photographer, or traveler. Make this village your creative base, explore new destinations, and create something unique. Lekhak Gaon offers facilities like writer's cottages, a residential complex, a library, an art gallery, a yoga and meditation center, a discussion hub, and a recreation center—all designed to invigorate your mind and spirit. More than just an infrastructure, this initiative aims to honor outstanding writers and creators whose artistic journey has been hindered by challenges. It will also nurture and develop the skills of emerging talents, fostering a thriving creative community.`,
  },
  {
    id: 3,
    title: `विभिन्न क्षेत्रों में कार्य करने वाले अनुभवी चाहे वे प्रशासनिक,सामाजिक, साहित्यिक,सांस्कृतिक  आदि विषयों से संबंध रखते हों उनके अनुभवों के संरक्षण और प्रकाशन में लेखक गांव सहायता करेगा। यह केंद्र परम्परागत ज्ञान परम्परा को सजोने के साथ साथ साहित्य संस्कृति एवम कला महोत्सवों का नियमित अंतराल में आयोजन करते हुए स्वस्थ मनोरंज और विचार विमर्श से रचनात्मकता को विस्तार प्रदान करने का प्रयास कर रहा है. लेखक गांव उन सबके लिए सहायता,सहयोग ,सानिध्य और सृजन का आधार प्रदान करता है जिनके पास  योग्यता तथा प्रखरता है किंतु अवसर और परिवेश उपलब्ध नहीं तो आइए लेखक गांव का अंग बनिए और दीजिए अपनी कल्पनाओं को विस्तार स्पर्श हिमालय अभियान के साथ।`,
    title2: `Lekhak Gaon will support the preservation and publication of the experiences of experts from various fields, whether administrative, social, literary, or cultural. Along with safeguarding traditional knowledge, this center will regularly organize literature, culture, and art festivals, fostering creativity through meaningful discussions and enriching entertainment. It serves as a foundation of support, collaboration, and inspiration for those with talent and brilliance but lacking opportunities and the right environment. Join Lekhak Gaon and give wings to your imagination through the "Sparsh Himalaya" initiative.`,
  },
];
